# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T08:57:00+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBasic, HTTPBearer
from fastapi import Header, Path, Query
from pydantic import conint
from starlette.requests import Request

from models import (
    By,
    ChannelDetails,
    ChannelsChannelIdMessagesGetResponse,
    ChannelsChannelIdMessagesPostResponse,
    ChannelsChannelIdPresenceGetResponse,
    ChannelsChannelIdPresenceHistoryGetResponse,
    ChannelsGetResponse,
    DeviceDetails,
    Direction,
    Error,
    Format,
    KeysKeyNameRequestTokenPostRequest,
    Message,
    PushChannelsGetResponse,
    PushChannelSubscriptionsPostRequest,
    PushPublishPostRequest,
    StatsGetResponse,
    TimeGetResponse,
    TokenDetails,
    Unit,
)

app = MCPProxy(
    contact={
        'email': 'support@ably.io',
        'name': 'Ably Support',
        'url': 'https://www.ably.io/contact',
        'x-twitter': 'ablyrealtime',
    },
    description='The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.',
    title='Platform API',
    version='1.1.0',
    servers=[{'url': 'https://rest.ably.io'}],
)


@app.get(
    '/channels',
    description=""" Enumerate all active channels of the application """,
    tags=['channel_metadata_management'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def get_metadata_of_all_channels(
    limit: Optional[int] = 100,
    prefix: Optional[str] = None,
    by: Optional[By] = None,
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    Enumerate all active channels of the application
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/channels/{channel_id}',
    description=""" Get metadata of a channel """,
    tags=['channel_metadata_management'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def get_metadata_of_channel(
    channel_id: str,
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    Get metadata of a channel
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/channels/{channel_id}/messages',
    description=""" Get message history for a channel """,
    tags=['channel_metadata_management'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def get_messages_by_channel(
    channel_id: str,
    start: Optional[str] = None,
    limit: Optional[int] = '100',
    end: Optional[str] = 'now',
    direction: Optional[Direction] = 'backwards',
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    Get message history for a channel
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/channels/{channel_id}/messages',
    description=""" Publish a message to the specified channel """,
    tags=['push_notification_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def publish_messages_to_channel(
    channel_id: str,
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
    body: Message = None,
):
    """
    Publish a message to a channel
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/channels/{channel_id}/presence',
    description=""" Get presence on a channel """,
    tags=['channel_presence_info'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def get_presence_of_channel(
    channel_id: str,
    client_id: Optional[str] = Query(None, alias='clientId'),
    connection_id: Optional[str] = Query(None, alias='connectionId'),
    limit: Optional[int] = 100,
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    Get presence of a channel
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/channels/{channel_id}/presence/history',
    description=""" Get presence on a channel """,
    tags=['channel_presence_info', 'channel_metadata_management'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def get_presence_history_of_channel(
    channel_id: str,
    start: Optional[str] = None,
    limit: Optional[int] = '100',
    end: Optional[str] = 'now',
    direction: Optional[Direction] = 'backwards',
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    Get presence history of a channel
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/keys/{keyName}/requestToken',
    description=""" This is the means by which clients obtain access tokens to use the service. You can see how to construct an Ably TokenRequest in the [Ably TokenRequest spec](https://www.ably.io/documentation/rest-api/token-request-spec) documentation, although we recommend you use an Ably SDK rather to create a TokenRequest, as the construction of a TokenRequest is complex. The resulting token response object contains the token properties as defined in Ably TokenRequest spec. Authentication is not required if using a Signed TokenRequest. """,
    tags=['access_token_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def request_access_token(
    key_name: str = Path(..., alias='keyName'),
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
    body: KeysKeyNameRequestTokenPostRequest = None,
):
    """
    Request an access token
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/push/channelSubscriptions',
    description=""" Delete a device details object. """,
    tags=['push_notification_services', 'device_registration_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def delete_push_device_details(
    channel: Optional[str] = None,
    device_id: Optional[str] = Query(None, alias='deviceId'),
    client_id: Optional[str] = Query(None, alias='clientId'),
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    Delete a registered device's update token
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/push/channelSubscriptions',
    description=""" Get a list of push notification subscriptions to channels. """,
    tags=['channel_metadata_management', 'push_notification_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def get_push_subscriptions_on_channels(
    channel: Optional[str] = None,
    device_id: Optional[str] = Query(None, alias='deviceId'),
    client_id: Optional[str] = Query(None, alias='clientId'),
    limit: Optional[conint(le=1000)] = 100,
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    List channel subscriptions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/push/channelSubscriptions',
    description=""" Subscribe either a single device or all devices associated with a client ID to receive push notifications from messages sent to a channel. """,
    tags=['push_notification_services', 'device_registration_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def subscribe_push_device_to_channel(
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
    body: PushChannelSubscriptionsPostRequest = None,
):
    """
    Subscribe a device to a channel
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/push/channels',
    description=""" Returns a paginated response of channel names. """,
    tags=['channel_metadata_management', 'channel_presence_info'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def get_channels_with_push_subscribers(
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    List all channels with at least one subscribed device
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/push/deviceRegistrations',
    description=""" Unregisters devices. All their subscriptions for receiving push notifications through channels will also be deleted. """,
    tags=['push_notification_services', 'device_registration_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def unregister_all_push_devices(
    device_id: Optional[str] = Query(None, alias='deviceId'),
    client_id: Optional[str] = Query(None, alias='clientId'),
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    Unregister matching devices for push notifications
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/push/deviceRegistrations',
    description=""" List of device details of devices registed for push notifications. """,
    tags=['push_notification_services', 'device_registration_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def get_registered_push_devices(
    device_id: Optional[str] = Query(None, alias='deviceId'),
    client_id: Optional[str] = Query(None, alias='clientId'),
    limit: Optional[conint(le=1000)] = 100,
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    List devices registered for receiving push notifications
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/push/deviceRegistrations',
    description=""" Register a device’s details, including the information necessary to deliver push notifications to it. Requires "push-admin" capability. """,
    tags=['push_notification_services', 'device_registration_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def register_push_device(
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
    body: DeviceDetails = None,
):
    """
    Register a device for receiving push notifications
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/push/deviceRegistrations/{device_id}',
    description=""" Unregisters a single device by its device ID. All its subscriptions for receiving push notifications through channels will also be deleted. """,
    tags=['push_notification_services', 'device_registration_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def unregister_push_device(
    device_id: str,
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    Unregister a single device for push notifications
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/push/deviceRegistrations/{device_id}',
    description=""" Get the full details of a device. """,
    tags=['device_registration_services', 'push_notification_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def get_push_device_details(
    device_id: str,
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    Get a device registration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/push/deviceRegistrations/{device_id}',
    description=""" Specific attributes of an existing registration can be updated. Only clientId, metadata and push.recipient are mutable. """,
    tags=['device_registration_services', 'push_notification_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def patch_push_device_details(
    device_id: str,
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
    body: DeviceDetails = None,
):
    """
    Update a device registration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/push/deviceRegistrations/{device_id}',
    description=""" Device registrations can be upserted (the existing registration is replaced entirely) with a PUT operation. Only clientId, metadata and push.recipient are mutable. """,
    tags=['device_registration_services', 'push_notification_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def put_push_device_details(
    device_id: str,
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
    body: DeviceDetails = None,
):
    """
    Update a device registration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/push/deviceRegistrations/{device_id}/resetUpdateToken',
    description=""" Gets an updated device details object. """,
    tags=['device_registration_services', 'push_notification_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def update_push_device_details(
    device_id: str,
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    Reset a registered device's update token
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/push/publish',
    description=""" A convenience endpoint to deliver a push notification payload to a single device or set of devices identified by their client identifier. """,
    tags=['push_notification_services'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def publish_push_notification_to_devices(
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
    body: PushPublishPostRequest = None,
):
    """
    Publish a push notification to device(s)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/stats',
    description=""" The Ably system can be queried to obtain usage statistics for a given application, and results are provided aggregated across all channels in use in the application in the specified period. Stats may be used to track usage against account quotas. """,
    tags=['application_usage_statistics'],
    security=[
        HTTPBasic(name="None"),
        HTTPBearer(name="None"),
    ],
)
def get_stats(
    start: Optional[str] = None,
    limit: Optional[int] = '100',
    end: Optional[str] = 'now',
    direction: Optional[Direction] = 'backwards',
    unit: Optional[Unit] = 'minute',
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    Retrieve usage statistics for an application
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/time',
    description=""" This returns the service time in milliseconds since the epoch. """,
    tags=['application_usage_statistics'],
)
def get_time(
    x__ably__version: Optional[str] = Header(None, alias='X-Ably-Version'),
    format: Optional[Format] = None,
):
    """
    Get the service time
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
