# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T08:57:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, RootModel


class FormFactor(Enum):
    phone = 'phone'
    tablet = 'tablet'
    desktop = 'desktop'
    tv = 'tv'
    watch = 'watch'
    car = 'car'
    embedded = 'embedded'


class Platform(Enum):
    ios = 'ios'
    android = 'android'


class PushState(Enum):
    Active = 'Active'
    Failing = 'Failing'
    Failed = 'Failed'


class Error(BaseModel):
    code: Optional[int] = Field(None, description='Error code.')
    href: Optional[str] = Field(None, description='Link to help with error.')
    message: Optional[str] = Field(
        None, description="Message explaining the error's cause."
    )
    serverId: Optional[str] = Field(
        None, description='Server ID with which error was encountered.'
    )
    statusCode: Optional[int] = Field(None, description='Status error code.')


class Notification(BaseModel):
    body: Optional[str] = Field(
        None, description='Text below title on the expanded notification.'
    )
    collapseKey: Optional[str] = Field(
        None, description='Platform-specific, used to group notifications together.'
    )
    icon: Optional[str] = Field(
        None, description='Platform-specific icon for the notification.'
    )
    sound: Optional[str] = Field(
        None, description='Platform-specific sound for the notification.'
    )
    title: Optional[str] = Field(
        None, description='Title to display at the notification.'
    )


class Occupancy(BaseModel):
    presenceConnections: Optional[int] = Field(
        None,
        description='The number of connections that are authorised to enter members into the presence channel.',
    )
    presenceMembers: Optional[int] = Field(
        None,
        description='The number of members currently entered into the presence channel.',
    )
    presenceSubscribers: Optional[int] = Field(
        None,
        description='The number of connections that are authorised to subscribe to presence messages.',
    )
    publishers: Optional[int] = Field(
        None,
        description='The number of connections attached to the channel that are authorised to publish.',
    )
    subscribers: Optional[int] = Field(
        None,
        description='The number of connections attached that are authorised to subscribe to messages.',
    )


class Action(Enum):
    ABSENT = 'ABSENT'
    PRESENT = 'PRESENT'
    ENTER = 'ENTER'
    LEAVE = 'LEAVE'
    UPDATE = 'UPDATE'


class Apns(BaseModel):
    notification: Optional[Notification] = None


class Fcm(BaseModel):
    notification: Optional[Notification] = None


class Web(BaseModel):
    notification: Optional[Notification] = None


class Push(BaseModel):
    apns: Optional[Apns] = Field(
        None,
        description='Extends and overrides generic values when delivering via APNs. [See examples](https://www.ably.io/documentation/general/push/publish#payload-structure)',
    )
    data: Optional[str] = Field(
        None,
        description='Arbitrary [key-value string-to-string payload](https://www.ably.io/documentation/general/push/publish#channel-broadcast-example).',
    )
    fcm: Optional[Fcm] = Field(
        None,
        description='Extends and overrides generic values when delivering via GCM/FCM. [See examples](https://www.ably.io/documentation/general/push/publish#payload-structure)',
    )
    notification: Optional[Notification] = None
    web: Optional[Web] = Field(
        None,
        description='Extends and overrides generic values when delivering via web. [See examples](https://www.ably.io/documentation/general/push/publish#payload-structure)',
    )


class TransportType(Enum):
    apns = 'apns'
    fcm = 'fcm'
    gcm = 'gcm'


class Recipient(BaseModel):
    clientId: Optional[str] = Field(None, description='Client ID of recipient')
    deviceId: Optional[str] = Field(None, description='Client ID of recipient')
    deviceToken: Optional[str] = Field(
        None, description='when using APNs, specifies the required device token.'
    )
    registrationToken: Optional[str] = Field(
        None,
        description='when using GCM or FCM, specifies the required registration token.',
    )
    transportType: Optional[TransportType] = Field(
        None, description='Defines which push platform is being used.'
    )


class TokenDetails(BaseModel):
    capability: Optional[str] = Field(
        None,
        description='Regular expression representation of the capabilities of the token.',
    )
    expires: Optional[int] = Field(None, description='Timestamp of token expiration.')
    issued: Optional[int] = Field(None, description='Timestamp of token creation.')
    keyName: Optional[str] = Field(
        None, description='Name of the key used to create the token'
    )
    token: Optional[str] = Field(None, description='The Ably Token.')


class TokenRequest(BaseModel):
    capability: Dict[str, Any] = Field(
        ...,
        description='The [capabilities](https://www.ably.io/documentation/core-features/authentication#capabilities-explained) (i.e. a set of channel names/namespaces and, for each, a set of operations) which should be a subset of the set of capabilities associated with the key specified in keyName.',
        examples=[{'channel1': ['publish', 'subscribe']}],
    )
    clientId: Optional[str] = Field(
        None,
        description='The [client ID](https://www.ably.io/documentation/core-features/authentication#identified-clients) to be assosciated with the token. Can be set to * to allow for any client ID to be used.',
    )
    keyName: str = Field(
        ...,
        description='Name of the key used for the TokenRequest. The keyName comprises of the app ID and key ID on an API Key.',
        examples=['xVLyHw.LMJZxw'],
    )
    nonce: str = Field(
        ...,
        description='An unquoted, un-escaped random string of at least 16 characters. Used to ensure the Ably TokenRequest cannot be reused.',
    )
    timestamp: int = Field(
        ..., description='Time of creation of the Ably TokenRequest.'
    )


class By(Enum):
    value = 'value'
    id = 'id'


class Format(Enum):
    json = 'json'
    jsonp = 'jsonp'
    msgpack = 'msgpack'
    html = 'html'


class Direction(Enum):
    forwards = 'forwards'
    backwards = 'backwards'


class ChannelsChannelIdMessagesPostResponse(BaseModel):
    channel: Optional[str] = None
    messageId: Optional[str] = None


class PushChannelSubscriptionsPostRequest1(BaseModel):
    channel: Optional[str] = Field(None, description='Channel name.')
    deviceId: Optional[str] = Field(
        None,
        description='Must be set when clientId is empty, cannot be used with clientId.',
    )


class PushChannelSubscriptionsPostRequest2(BaseModel):
    channel: Optional[str] = Field(None, description='Channel name.')
    clientId: Optional[str] = Field(
        None,
        description='Must be set when deviceId is empty, cannot be used with deviceId.',
    )


class PushChannelSubscriptionsPostRequest(
    RootModel[
        Union[
            PushChannelSubscriptionsPostRequest1, PushChannelSubscriptionsPostRequest2
        ]
    ]
):
    root: Union[
        PushChannelSubscriptionsPostRequest1, PushChannelSubscriptionsPostRequest2
    ]


class PushChannelSubscriptionsPostRequest4(BaseModel):
    channel: Optional[str] = Field(None, description='Channel name.')
    deviceId: Optional[str] = Field(
        None,
        description='Must be set when clientId is empty, cannot be used with clientId.',
    )


class PushChannelSubscriptionsPostRequest5(BaseModel):
    channel: Optional[str] = Field(None, description='Channel name.')
    clientId: Optional[str] = Field(
        None,
        description='Must be set when deviceId is empty, cannot be used with deviceId.',
    )


class PushChannelSubscriptionsPostRequest3(
    RootModel[
        Union[
            PushChannelSubscriptionsPostRequest4, PushChannelSubscriptionsPostRequest5
        ]
    ]
):
    root: Union[
        PushChannelSubscriptionsPostRequest4, PushChannelSubscriptionsPostRequest5
    ]


class PushChannelSubscriptionsPostRequest7(BaseModel):
    channel: Optional[str] = Field(None, description='Channel name.')
    deviceId: Optional[str] = Field(
        None,
        description='Must be set when clientId is empty, cannot be used with clientId.',
    )


class PushChannelSubscriptionsPostRequest8(BaseModel):
    channel: Optional[str] = Field(None, description='Channel name.')
    clientId: Optional[str] = Field(
        None,
        description='Must be set when deviceId is empty, cannot be used with deviceId.',
    )


class PushChannelSubscriptionsPostRequest6(
    RootModel[
        Union[
            PushChannelSubscriptionsPostRequest7, PushChannelSubscriptionsPostRequest8
        ]
    ]
):
    root: Union[
        PushChannelSubscriptionsPostRequest7, PushChannelSubscriptionsPostRequest8
    ]


class PushChannelsGetResponse(RootModel[List[str]]):
    root: List[str]


class PushPublishPostRequest(BaseModel):
    push: Optional[Push] = None
    recipient: Recipient


class Unit(Enum):
    minute = 'minute'
    hour = 'hour'
    day = 'day'
    month = 'month'


class StatsGetResponse(BaseModel):
    pass


class TimeGetResponse(RootModel[List[int]]):
    root: List[int]


class ChannelStatus(BaseModel):
    isActive: bool = Field(
        ...,
        description='A required boolean value indicating whether the channel that is the subject of the event is active. For events indicating regional activity of a channel this indicates activity in that region, not global activity.',
    )
    occupancy: Optional[Occupancy] = None


class DeviceDetails(BaseModel):
    clientId: Optional[str] = Field(
        None, description='Optional trusted client identifier for the device.'
    )
    deviceSecret: Optional[str] = Field(
        None, description='Secret value for the device.'
    )
    formFactor: Optional[FormFactor] = Field(
        None, description='Form factor of the push device.'
    )
    id: Optional[str] = Field(
        None,
        description='Unique identifier for the device generated by the device itself.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Optional metadata object for this device. The metadata for a device may only be set by clients with push-admin privileges and will be used more extensively in the future with smart notifications.',
    )
    platform: Optional[Platform] = Field(
        None, description='Platform of the push device.'
    )
    push_recipient: Optional[Recipient] = Field(None, alias='push.recipient')
    push_state: Optional[PushState] = Field(
        None, alias='push.state', description='the current state of the push device.'
    )


class Extras(BaseModel):
    push: Optional[Push] = None


class Message(BaseModel):
    clientId: Optional[str] = Field(
        None,
        description='The [client ID](https://www.ably.io/documentation/core-features/authentication#identified-clients) of the publisher of this message.',
    )
    connectionId: Optional[str] = Field(
        None, description='The connection ID of the publisher of this message.'
    )
    data: Optional[str] = Field(
        None,
        description='The string encoded payload, with the encoding specified below.',
    )
    encoding: Optional[str] = Field(
        None,
        description='This will typically be empty as all messages received from Ably are automatically decoded client-side using this value. However, if the message encoding cannot be processed, this attribute will contain the remaining transformations not applied to the data payload.',
    )
    extras: Optional[Extras] = None
    id: Optional[str] = Field(
        None,
        description='A Unique ID that can be specified by the publisher for [idempotent publishing](https://www.ably.io/documentation/rest/messages#idempotent).',
    )
    name: Optional[str] = Field(None, description='The event name, if provided.')
    timestamp: Optional[int] = Field(
        None,
        description='Timestamp when the message was received by the Ably, as milliseconds since the epoch.',
    )


class PresenceMessage(BaseModel):
    action: Optional[Action] = Field(
        None, description='The event signified by a PresenceMessage.'
    )
    clientId: Optional[str] = Field(
        None, description='The client ID of the publisher of this presence update.'
    )
    connectionId: Optional[str] = Field(
        None, description='The connection ID of the publisher of this presence update.'
    )
    data: Optional[str] = Field(
        None, description='The presence update payload, if provided.'
    )
    encoding: Optional[str] = Field(
        None,
        description='This will typically be empty as all presence updates received from Ably are automatically decoded client-side using this value. However, if the message encoding cannot be processed, this attribute will contain the remaining transformations not applied to the data payload.',
    )
    extras: Optional[Extras] = None
    id: Optional[str] = Field(
        None, description='Unique ID assigned by Ably to this presence update.'
    )
    timestamp: Optional[int] = Field(
        None,
        description='Timestamp when the presence update was received by Ably, as milliseconds since the epoch.',
    )


class SignedTokenRequest(TokenRequest):
    mac: str = Field(
        ...,
        description='A signature, generated as an HMAC of each of the above components, using the key secret value.',
    )


class ChannelsChannelIdMessagesGetResponse(RootModel[List[Message]]):
    root: List[Message]


class ChannelsChannelIdPresenceGetResponse(RootModel[List[PresenceMessage]]):
    root: List[PresenceMessage]


class ChannelsChannelIdPresenceHistoryGetResponse(RootModel[List[PresenceMessage]]):
    root: List[PresenceMessage]


class KeysKeyNameRequestTokenPostRequest(
    RootModel[Union[TokenRequest, SignedTokenRequest]]
):
    root: Union[TokenRequest, SignedTokenRequest]


class ChannelDetails(BaseModel):
    channelId: str = Field(
        ...,
        description='The required name of the channel including any qualifier, if any.',
    )
    isGlobalMaster: Optional[bool] = Field(
        None,
        description='In events relating to the activity of a channel in a specific region, this optionally identifies whether or not that region is responsible for global coordination of the channel.',
    )
    region: Optional[str] = Field(
        None,
        description='In events relating to the activity of a channel in a specific region, this optionally identifies the region.',
    )
    status: Optional[ChannelStatus] = None


class ChannelsGetResponse(RootModel[Union[List[ChannelDetails], List[str]]]):
    root: Union[List[ChannelDetails], List[str]]
